<app:FIXML schemalocation="http://www.finacle.com/fixml">
	<app:Header>
		<app:RequestHeader>
			<app:MessageKey>
				<app:RequestUUID>${headers.UUID}</app:RequestUUID>
				<app:ServiceRequestId>executeFinacleScript</app:ServiceRequestId>
				<app:ServiceRequestVersion>10.2</app:ServiceRequestVersion>
				<app:ChannelId>POL</app:ChannelId>
				<app:LanguageId/>
			</app:MessageKey>
			<app:RequestMessageInfo>
				<app:BankId>${headers.bankId}</app:BankId>
				<app:TimeZone/>
				<app:EntityId/>
				<app:EntityType/>
				<app:ArmCorrelationId/>
				<app:MessageDateTime>${headers.messageDateTime}</app:MessageDateTime>
			</app:RequestMessageInfo>
			<app:Security>
				<app:Token>
					<app:PasswordToken>
						<app:UserId/>
						<app:Password/>
					</app:PasswordToken>
				</app:Token>
				<app:FICertToken/>
				<app:RealUserLoginSessionId/>
				<app:RealUser/>
				<app:RealUserPwd/>
				<app:SSOTransferToken/>
			</app:Security>
		</app:RequestHeader>
	</app:Header>
	<app:Body>
		<app:executeFinacleScriptRequest>
			<app:ExecuteFinacleScriptInputVO>
				<app:requestId>CustAcctInquiry</app:requestId>
			</app:ExecuteFinacleScriptInputVO>
			<app:executeFinacleScript_CustomData>
				<app:CustAcctInquiry_REQ>
					<app:BankID>${headers.bankId}</app:BankID>
					<app:AccountID>${headers.accountId}</app:AccountID>
				</app:CustAcctInquiry_REQ>
			</app:executeFinacleScript_CustomData>
		</app:executeFinacleScriptRequest>
	</app:Body>
</app:FIXML>