package com.zenith.accountInfo.commons;

public class Examples {

	public Examples() {
		throw new UnsupportedOperationException("Utility class");
	}

	public static final String REQUEST_EXAMPLE = "{\n"
			+ "  \"header\": {\n"
			+ "    \"messageID\": \"KCB_MESSAGEID\",\n"
			+ "    \"serviceCode\": \"1001\",\n"
			+ "    \"serviceName\": \"AccountInfo\",\n"
			+ "    \"channelCode\": \"101\",\n"
			+ "    \"channelName\": \"EzzyBizz\",\n"
			+ "    \"channelIdentifier\": \"POL\",\n"
			+ "    \"routeCode\": \"001\",\n"
			+ "    \"routeName\": \"Finacle\",\n"
			+ "    \"timeStamp\": \"2022-07-12T13:07:09.676\",\n"
			+ "    \"serviceMode\": \"sync\",\n"
			+ "    \"subscribeEvents\": \"1\",\n"
			+ "    \"callBackURL\": \"\"\n"
			+ "  },\n"
			+ "  \"requestPayload\": {\n"
			+ "    \"primaryData\": {\n"
			+ "      \"businessKey\": \"0540279760704\",\n"
			+ "      \"businessKeyType\": \"AccountNumber\"\n"
			+ "    },\n"
			+ "    \"additionalData\": {\n"
			+ "      \"bankId\": \"54\"\n"
			+ "    }\n"
			+ "  }\n"
			+ "}";
	
	
	
	

	public static final String RESPONSE_OK = "{\n"
			+ "    \"header\": {\n"
			+ "        \"messageID\": \"KCB_MESSAGEID\",\n"
			+ "        \"conversationID\": \"1e6b0bcc-e043-4e7d-a06b-ba42319a18cc\",\n"
			+ "        \"targetSystemID\": \"NotAvailable\",\n"
			+ "        \"channelCode\": \"101\",\n"
			+ "        \"channelName\": \"EzzyBizz\",\n"
			+ "        \"channelIdentifier\": \"POL\",\n"
			+ "        \"routeCode\": \"001\",\n"
			+ "        \"routeName\": \"Finacle\",\n"
			+ "        \"serviceCode\": \"1001\",\n"
			+ "        \"ehfInfo\": {\n"
			+ "            \"item\": [\n"
			+ "                {\n"
			+ "                    \"ehfRef\": \"OSP-1000\",\n"
			+ "                    \"ehfDesc\": \"Processed Successfully\"\n"
			+ "                }\n"
			+ "            ]\n"
			+ "        }\n"
			+ "    },\n"
			+ "    \"responsePayload\": {\n"
			+ "        \"primaryData\": {\n"
			+ "            \"businessKey\": \"0540279760704\",\n"
			+ "            \"businessKeyType\": \"AccountNumber\"\n"
			+ "        },\n"
			+ "        \"accountInfo\": {\n"
			+ "            \"customerDetails\": {\n"
			+ "                \"identifier\": \"54314582110\",\n"
			+ "                \"fullName\": \"SEERBIT LIMITED\",\n"
			+ "                \"firstName\": \"\",\n"
			+ "                \"lastName\": \"SEERBIT LIMITED\",\n"
			+ "                \"shortName\": \"SEERBIT\",\n"
			+ "                \"titleCode\": \"M/S\",\n"
			+ "                \"nationalID\": \"\",\n"
			+ "                \"emailID\": \"testdb@testdb.com\",\n"
			+ "                \"phoneNumber\": \"000000\",\n"
			+ "                \"dateOfBirth\": \"2020-02-25T12:00:00.000\",\n"
			+ "                \"maritalStatus\": \"\",\n"
			+ "                \"gender\": \"\",\n"
			+ "                \"minorFlag\": \"\",\n"
			+ "                \"nreFlag\": \"C\",\n"
			+ "                \"community\": \"\",\n"
			+ "                \"userSubClassification\": \"\",\n"
			+ "                \"passportNo\": \"\"\n"
			+ "            },\n"
			+ "            \"address\": {\n"
			+ "                \"addressLine1\": \"1\",\n"
			+ "                \"addressLine2\": \"1,NAIROBI\",\n"
			+ "                \"cityCode\": \"247\",\n"
			+ "                \"stateCode\": \"CEN\",\n"
			+ "                \"countryCode\": \"KE\",\n"
			+ "                \"cityCodeDesc\": \"OTHERS NOT DEFINED\",\n"
			+ "                \"pinCode\": \"00800\",\n"
			+ "                \"addressID\": \"81584351\"\n"
			+ "            },\n"
			+ "            \"accountID\": \"0540279760704\",\n"
			+ "            \"cbsAccountRef\": \"DV35367769\",\n"
			+ "            \"openDate\": \"2020-04-01T12:00:00.000\",\n"
			+ "            \"branchCode\": \"054\",\n"
			+ "            \"schemeCode\": \"CA210\",\n"
			+ "            \"schemeType\": \"CAA\",\n"
			+ "            \"accountName\": \"SEERBIT LIMITED\",\n"
			+ "            \"currency\": \"KES\",\n"
			+ "            \"statusCode\": \"A\",\n"
			+ "            \"ownershipCode\": \"C\",\n"
			+ "            \"closureFlag\": \"N\",\n"
			+ "            \"creationFlag\": \"Y\",\n"
			+ "            \"freezeCode\": \"\",\n"
			+ "            \"clearBalance\": \"2697584.46\",\n"
			+ "            \"unclearBalance\": \"-1630.20\",\n"
			+ "            \"effectiveBalance\": \"1693834.26\",\n"
			+ "            \"sanctionLimit\": \"0.00\",\n"
			+ "            \"lienAmount\": \"1000000.00\",\n"
			+ "            \"drawingPower\": \"0.00\",\n"
			+ "            \"modeOfOperation\": \"ETS\",\n"
			+ "            \"corpRetFlag\": \"C\",\n"
			+ "            \"incoprationDate\": \"2020-02-25T12:00:00.000\",\n"
			+ "            \"constCode\": \"\",\n"
			+ "            \"secRegNo\": \"CONS\",\n"
			+ "            \"compRegNo\": \"PVT-6LUXY7D\"\n"
			+ "        }\n"
			+ "    }\n"
			+ "}";

	public static final String RESPONSE_NOT_OK = "{\n"
			+ "	\"header\": {\n"
			+ "		\"messageID\": \"KCB_MESSAGEID\",\n"
			+ "		\"conversationID\": \"50697c9c-e129-4071-b323-a6640296fee1\",\n"
			+ "		\"targetSystemID\": \"not available\",\n"
			+ "		\"channelCode\":\"101\",\n"
			+ "		\"channelName\":\"EzzyBizz\",\n"
			+ "		\"channelIdentifier\":\"POL\",\n"
			+ "		\"routeCode\": \"001\",\n"
			+ "		\"routeName\": \"Finacle\",\n"
			+ "		\"serviceCode\":\"1001\",\n"
			+ "		\n"
			+ "		\"ehfInfo\": {\n"
			+ "			\"item\": [\n"
			+ "				{\n"
			+ "					\"ehfRef\": \"EHF-1001\",\n"
			+ "					\"ehfDesc\": \"Failure\"\n"
			+ "				} \n"
			+ "			]\n"
			+ "		}\n"
			+ "	},\n"
			+ "	\"responsePayload\": {\n"
			+ "		\"primaryData\": {\n"
			+ "			\n"
			+ "			\"businessKey\": \"2323\",\n"
			+ "			\"businessKeyType\": \"AccountNumber\"\n"
			+ "		} \n"
			+ "	}\n"
			+ "}";

	public static final String SUCCESSFUL_RESPONSE = "<FIXML xsi:schemaLocation=\"http://www.finacle.com/fixml executeFinacleScript.xsd\">\n"
			+ "	<Header>\n"
			+ "		<ResponseHeader>\n"
			+ "			<RequestMessageKey>\n"
			+ "				<RequestUUID>216620bf1752493780e222334a76b674-1</RequestUUID>\n"
			+ "				<ServiceRequestId>executeFinacleScript</ServiceRequestId>\n"
			+ "				<ServiceRequestVersion>10.2</ServiceRequestVersion>\n"
			+ "				<ChannelId>POL</ChannelId>\n"
			+ "			</RequestMessageKey>\n"
			+ "			<ResponseMessageInfo>\n"
			+ "				<BankId>54</BankId>\n"
			+ "				<TimeZone>GMT+05:30</TimeZone>\n"
			+ "				<MessageDateTime>2022-07-12T13:07:09.676</MessageDateTime>\n"
			+ "			</ResponseMessageInfo>\n"
			+ "			<UBUSTransaction>\n"
			+ "				<Id/>\n"
			+ "				<Status/>\n"
			+ "			</UBUSTransaction>\n"
			+ "			<HostTransaction>\n"
			+ "				<Id/>\n"
			+ "				<Status>SUCCESS</Status>\n"
			+ "			</HostTransaction>\n"
			+ "			<HostParentTransaction>\n"
			+ "				<Id/>\n"
			+ "				<Status/>\n"
			+ "			</HostParentTransaction>\n"
			+ "			<CustomInfo/>\n"
			+ "		</ResponseHeader>\n"
			+ "	</Header>\n"
			+ "	<Body>\n"
			+ "		<executeFinacleScriptResponse>\n"
			+ "			<ExecuteFinacleScriptOutputVO/>\n"
			+ "			<executeFinacleScript_CustomData>\n"
			+ "				<CustAcctInquiry_RES>\n"
			+ "					<CustomerID>54314582110</CustomerID>\n"
			+ "					<CustomerName>SEERBIT LIMITED</CustomerName>\n"
			+ "					<CustomerFirstName/>\n"
			+ "					<CustomerLastName>SEERBIT LIMITED</CustomerLastName>\n"
			+ "					<CustomerShortName>SEERBIT</CustomerShortName>\n"
			+ "					<CustomerTitleCode>M/S</CustomerTitleCode>\n"
			+ "					<NationalID/>\n"
			+ "					<EmailID>testdb@testdb.com</EmailID>\n"
			+ "					<PhoneNo>000000</PhoneNo>\n"
			+ "					<DateOfBirth>2020-02-25T12:00:00.000</DateOfBirth>\n"
			+ "					<MaritalStatus/>\n"
			+ "					<Sex/>\n"
			+ "					<CustomerMinorFlag/>\n"
			+ "					<CustomerNREFlag/>\n"
			+ "					<Community/>\n"
			+ "					<UserSubClassification/>\n"
			+ "					<PassportNo/>\n"
			+ "					<PrefAddress>\n"
			+ "						<Address1>1</Address1>\n"
			+ "						<Address2>1,NAIROBI</Address2>\n"
			+ "						<CityCode>247</CityCode>\n"
			+ "						<StateCode>CEN</StateCode>\n"
			+ "						<CountryCode>KE</CountryCode>\n"
			+ "						<CityCodeDesc>OTHERS NOT DEFINED</CityCodeDesc>\n"
			+ "						<PinCode>00800</PinCode>\n"
			+ "						<AddressId>81584351</AddressId>\n"
			+ "					</PrefAddress>\n"
			+ "					<AcctDtls>\n"
			+ "						<AccountID>0540279760704</AccountID>\n"
			+ "						<Acid>DV35367769</Acid>\n"
			+ "						<AcctOpenDate>2020-04-01T12:00:00.000</AcctOpenDate>\n"
			+ "						<BranchCode>054</BranchCode>\n"
			+ "						<SchemeCode>CA210</SchemeCode>\n"
			+ "						<SchemeType>CAA</SchemeType>\n"
			+ "						<AccountName>SEERBIT LIMITED</AccountName>\n"
			+ "						<Currency>KES</Currency>\n"
			+ "						<AccountStatus>A</AccountStatus>\n"
			+ "						<AccountOwnership>C</AccountOwnership>\n"
			+ "						<AccountClosureFlag>N</AccountClosureFlag>\n"
			+ "						<AccountCreationFlag>Y</AccountCreationFlag>\n"
			+ "						<FreezeCode/>\n"
			+ "						<ClearBalance>2697584.46</ClearBalance>\n"
			+ "						<UnclearBalance>-1630.20</UnclearBalance>\n"
			+ "						<EffectiveBalance>1693834.26</EffectiveBalance>\n"
			+ "						<SanctionLimit>0.00</SanctionLimit>\n"
			+ "						<LienAmount>1000000.00</LienAmount>\n"
			+ "						<DrawingPower>0.00</DrawingPower>\n"
			+ "						<ModeOfOperation>ETS</ModeOfOperation>\n"
			+ "					</AcctDtls>\n"
			+ "					<RetCorpFlg>C</RetCorpFlg>\n"
			+ "					<DateOfIncorp>2020-02-25T12:00:00.000</DateOfIncorp>\n"
			+ "					<ConstCode/>\n"
			+ "					<SecRegNo>CONS</SecRegNo>\n"
			+ "					<CompRegNo>PVT-6LUXY7D</CompRegNo>\n"
			+ "				</CustAcctInquiry_RES>\n"
			+ "			</executeFinacleScript_CustomData>\n"
			+ "		</executeFinacleScriptResponse>\n"
			+ "	</Body>\n"
			+ "</FIXML>";

	public static final String ERROR_RESPONSE = "<FIXML xsi:schemaLocation=\"http://www.finacle.com/fixml executeFinacleScript.xsd\">\n"
			+ "	<Header>\n"
			+ "		<ResponseHeader>\n"
			+ "			<RequestMessageKey>\n"
			+ "				<RequestUUID>216620bf1752493780e222334a76b674-1</RequestUUID>\n"
			+ "				<ServiceRequestId>executeFinacleScript</ServiceRequestId>\n"
			+ "				<ServiceRequestVersion>10.2</ServiceRequestVersion>\n"
			+ "				<ChannelId>POL</ChannelId>\n"
			+ "			</RequestMessageKey>\n"
			+ "			<ResponseMessageInfo>\n"
			+ "				<BankId>54</BankId>\n"
			+ "				<TimeZone>GMT+05:30</TimeZone>\n"
			+ "				<MessageDateTime>2022-07-12T13:07:09.676</MessageDateTime>\n"
			+ "			</ResponseMessageInfo>\n"
			+ "			<UBUSTransaction>\n"
			+ "				<Id/>\n"
			+ "				<Status/>\n"
			+ "			</UBUSTransaction>\n"
			+ "			<HostTransaction>\n"
			+ "				<Id/>\n"
			+ "				<Status>ERROR</Status>\n"
			+ "			</HostTransaction>\n"
			+ "			<HostParentTransaction>\n"
			+ "				<Id/>\n"
			+ "				<Status/>\n"
			+ "			</HostParentTransaction>\n"
			+ "			<CustomInfo/>\n"
			+ "		</ResponseHeader>\n"
			+ "	</Header>\n"
			+ "	<Body></Body>\n"
			+ "</FIXML>";

}
